version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    expose:
      - 3306
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --log_bin_trust_function_creators=true
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - .mariadb.env

  nextcloud:
    image: bankaitech/nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - mariadb
      - redis
      - collabora
      - imaginary
      - go-vod
    volumes:
      - ./nextcloud:/var/www/html
    env_file:
      - .nextcloud.env

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
    command: redis-server --save 60 1 --loglevel warning
    restart: always

  collabora:
    container_name: collabora
    hostname: collabora
    privileged: true
    tty: true
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    image: collabora/code:latest
#    volumes:
#      - ./collabora/config/coolwsd.xml:/etc/coolwsd/coolwsd.xml
    env_file:
      - .collabora.env
    restart: always

  imaginary:
    image: nextcloud/aio-imaginary:latest
    container_name: imaginary
    restart: always
    environment:
      - PORT=9000
    ports:
      - 9000:9000
    command: -concurrency 50 -enable-url-source -log-level debug

  go-vod:
    image: radialapps/go-vod
    restart: always
    container_name: go-vod
    env_file:
      - .go_vod.env
    volumes:
      - ./nextcloud:/var/www/html:ro
#    runtime: nvidia # (NVENC)  # For Nvidia HW Acceleration, Uncomment after installing nvidia drivers. Test nvidia by running `sudo nvidia-smi`
