#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive

# Check the host's operating system
OS=$(uname -s)
if [ "$OS" = "Linux" ]; then
    # Check if the distribution is Ubuntu
    if [ -f /etc/lsb-release ]; then
        . /etc/lsb-release
        if [ "$DISTRIB_ID" != "Ubuntu" ]; then
            echo "Warning: This script has only been tested on Ubuntu."
            read -p "Do you want to continue? (y/N): " confirm
            if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
                echo "Exiting script."
                exit 1
            fi
        fi
    else
        echo "Warning: Unable to determine Linux distribution. This script has only been tested on Ubuntu."
        read -p "Do you want to continue? (y/N): " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Exiting script."
            exit 1
        fi
    fi
else
    echo "Unsupported operating system: $OS"
    echo "This script only works for Linux systems."
    read -p "Press ENTER to exit."
    exit 1
fi

# Prompt user for Nginx installation option
echo "Select the Nginx installation option:"
echo "1) Create nextcloud.conf file"
echo "2) Install Nginx and Configure for Nextcloud"
read -p "Enter your choice (1/2): " INSTALL_OPTION

# Check if Nginx is installed
if ! nginx -v &> /dev/null; then
    echo "Nginx is not installed. Installing Nginx..."
    sudo apt-get update
    sudo apt-get install -y nginx
    echo ""
    echo "Nginx has been installed."
else
    echo "Nginx is already installed."
fi

# Check if Certbot is installed
if ! command -v certbot &> /dev/null; then
    echo "Certbot is not installed. Installing Certbot..."
    sudo apt-get update
    sudo apt-get install -y certbot python3-certbot-nginx
    echo "Certbot has been installed."
else
    echo "Certbot is already installed."
fi

# Prompt user for Domain
echo ""
echo "What is your nextcloud domain? "
echo "Example: cloud.bankai-tech.com"
read -p "Enter your domain: " DOMAIN_NAME

# Prompt user for Collabora Domain
echo ""
echo "Will you be using Collabora (NC Office)? (y/N): "
read -p "Enter (y/N): " install_collabora
if [[ "$install_collabora" =~ ^[Yy]$ ]]; then
    echo ""
    echo "What is your collabora domain? "
    echo "Example: office.bankai-tech.com"
    read -p "Enter your domain: " COLLABORA_DOMAIN
fi

# Prompt user for Email
echo ""
echo "What is your email? "
read -p "Enter your email: " EMAIL

# Obtain SSL certificates for DOMAIN_NAME
echo "Obtaining SSL certificates for $DOMAIN_NAME..."
sudo certbot --nginx -d "$DOMAIN_NAME" --non-interactive --agree-tos -m "$EMAIL" --redirect

# Check if Collabora Domain is provided and obtain SSL certificates
if [[ "$install_collabora" =~ ^[Yy]$ ]]; then
    echo "Obtaining SSL certificates for $COLLABORA_DOMAIN..."
    sudo certbot --nginx -d "$COLLABORA_DOMAIN" --non-interactive --agree-tos -m "$EMAIL" --redirect
fi

echo "SSL certificates have been obtained successfully."
