name: media-management

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    depends_on:
      - prowlarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./radarr:/config
      - /media/Movies:/Movies #optional
      - /media/Downloads:/media/Downloads #optional
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 7878:7878
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    depends_on:
      - prowlarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./readarr:/config
      - /media/Books:/books #optional
      - /media/Downloads:/media/Downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - prowlarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./sonarr:/config
      - /media/TV:/TV #optional
      - /media/Downloads:/media/Downloads #optional
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    depends_on:
      - prowlarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./lidarr/config:/config
      - /media/Music:/music #optional
      - /media/Downloads:/media/Downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./prowlarr:/config
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr/config:/app/config
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
