name: prowlarr

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./prowlarr:/config
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 9696:9696
    restart: unless-stopped
