name: sonarr

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environtment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./sonarr:/config
      - /media/TV:/TV #optional
      - /media/Downloads:/media/Downloads #optional
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 8989:8989
    restart: unless-stopped
